version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=apiwebnews12
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql  # Sử dụng named volume
    networks:
      - app-network

  api:
    image: news-api-image
    container_name: springboot-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/apiwebnews12?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345678
    networks:
      - app-network

  react:
    image: news-react-image
    container_name: react-frontend
    ports:
      - "3000:80"
    depends_on:
      - api
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
